### ISSUE TITLE
Use object methods

### ISSUE THREAD

**Issue by tariqbuilds** [pnjoku/file-metadata#11]
- https://github.com/pnjoku/file-metadata/blob/master/server.js#L33
- https://github.com/pnjoku/file-metadata/blob/master/server.js#L36

Whenever you have a property of an object that is a function, use object methods:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

So, for example, this:

``` js
let storage = multer.diskStorage({
  destination: (req, file, cb) =>{
    cb(null, 'uploads/')
  },
...
```

would turn into:

``` js
let storage = multer.diskStorage({
  destination(req, file, cb) =>{
    cb(null, 'uploads/')
  },
...
```

**Comment by pnjoku** [comment]
it doesn't like my arrows

**Comment by tariqbuilds** [comment]
what version of node are you running? (`node -v`)

**Comment by pnjoku** [comment]
v4.4.5

**Comment by tariqbuilds** [comment]
I would suggest upgrading that to at least v6.0 or higher so you can get the latest security upgrades and ES6 syntax. 

Download link: https://nodejs.org/en/download/current/

v6.4 is the latest stable version and is slated to be LTS in a month.
https://github.com/nodejs/LTS#lts_schedule

**Comment by pnjoku** [comment]
![screen shot 2016-09-06 at 4 32 24 pm](https://cloud.githubusercontent.com/assets/6454202/18289953/907b9562-744f-11e6-9b79-acd1d1fe58ba.png)
I have the latest version of node

**Comment by tariqbuilds** [comment]
@pnjoku That's my bad. I had a typo in my example above. Arrows aren't needed for object methods. I must have copied & pasted from the previous, arrow Fn example. My bad.

Here is the correct snippet:

``` js
let storage = multer.diskStorage({
  destination(req, file, cb) {
    cb(null, 'uploads/')
  },
...
```

it is a shortcut for assigning a function to a property of an object. The old way:

``` js
let storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, 'uploads/')
  },
```

For short, one-liner functions inside of an object, you can still do arrow functions for even shorter syntax (like in #12 ):

``` js
let storage = multer.diskStorage({
  destination: () => cb(null, 'uploads/'),
...
```
